# Generated by Django 4.0.3 on 2022-04-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicecategory_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_main',
        ),
    ]
