# Generated by Django 4.0.3 on 2022-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_directioncategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default='4', upload_to='uploads/contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='file_name',
            field=models.CharField(default='4', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='file_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_name_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
