# Generated by Django 4.0.3 on 2022-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contact_file_contact_file_name_contact_file_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesettings',
            name='logo',
            field=models.FileField(upload_to='uploads/settings'),
        ),
    ]
