# Generated by Django 4.0.3 on 2022-04-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_service_icon_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projectcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='service_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.servicecategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='direction_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.directioncategory'),
        ),
    ]
